name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main # You can change it to whatever is your deployment branch

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: $ a95b92ae1d9e9b3860605bb16c1a9373d5996a10af76896be770acb23d9287cd2-59cf76dc-8539-40e8-bed9-89f1a45a1aa0010163777
          repo_token: $ # Used for GitHub integration
          action: "upload"
          app_location: "/" # This will typically be the repository root
          api_location: "" # No API here, therefore
          skip_api_build: true # skip API build
          output_location: "_site" # Modify this to where your SSG places the built HTML - could be `dist`, `build`... check your config
          app_build_command: 'yarn build' # Not necessary since the action will pick it up from 'package.json' but I like it explicit
